name: (Linux x64) build and test

on: 
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-qtcache

      - name: Get short SHA and set Qt version
        run: |
          echo SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8) >> $env:GITHUB_ENV
          echo QT_VERSION=5.15.2 >> $env:GITHUB_ENV

      - name: Install Qt if not cached
        id: install-qt
        if: steps.cache-qt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.QT_VERSION }}
        
      - name: Compile
        run: |
          PATH=${{ env:GITHUB_WORKSPACE }}/Qt/5.15.2/gcc_64/bin:$PATH
          rm -rf build
          mkdir -p build/debug
          cd build/debug
          qmake ../../trdrop/trdrop.pro -config debug
          make

      - name: Run tests
        run: |
          ./build/debug/trdrop-tests/trdrop-tests