name: (Linux x64) build, test and publish an AppImage

on: 
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build-linux:
    # TODO: Make linuxdeployqt work with ubuntu-20.04
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get short SHA and set Qt version
        run: |
          echo SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8) >> $GITHUB_ENV
          echo QT_VERSION=5.15.2 >> $GITHUB_ENV

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-Qt-${{ env.QT_VERSION }}-Cache

      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.QT_VERSION }} 
        
      - name: Compile
        run: |
          rm -rf build
          mkdir -p build/release
          cd build/release
          qmake ../../trdrop/trdrop.pro -config release
          make

      - name: Run tests
        run: |
          ./build/release/trdrop-tests/trdrop-tests

      - name: Create AppImage
        if: startsWith(github.event.head_commit.message, 'Release')
        run: |
          sudo apt install libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-bad
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          cp build/release/trdrop-ui/trdrop-ui linuxdeployqt-template/usr/bin
          cd linuxdeployqt-template
          ../linuxdeployqt-continuous-x86_64.AppImage usr/share/applications/trdrop.desktop -verbose=1 -appimage -qmldir=${{ env.QML2_IMPORT_PATH }}

      - name: Upload AppImage
        if: startsWith(github.event.head_commit.message, 'Release')
        uses: actions/upload-artifact@v2
        with:
          name: trdrop-${{ env.SHORT_SHA }}.AppImage
          path: linuxdeployqt-template/*.AppImage
