name: (Linux x64) build and test

on: 
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-qtcache

      - name: Get short SHA and set Qt version
        run: |
          echo SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8) >> $env:GITHUB_ENV
          echo QT_VERSION=5.15.2 >> $env:GITHUB_ENV

      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: 5.15.2
        
      - name: Compile
        run: |
          echo "pwd"
          pwd
          echo "ls"
          ls
          echo "ls .."
          ls ..
          rm -rf build
          mkdir -p build/debug
          cd build/debug
          pwd
          ls ..
          ls ../../
          qmake ../../trdrop/trdrop.pro -config debug
          make
          pwd

      - name: Run tests
        run: |
          pwd
          cd ../..
          ./build/debug/trdrop-tests/trdrop-tests