name: (Windows x64) build, test and publish

on: [push, pull_request]

#on: 
#  push:
#    branches: [ v2 ]


jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get short SHA and set Qt version
        run: |
          echo "SHORT_SHA=$($env:GITHUB_SHA.SubString(0,7))" >> $env:GITHUB_ENV
          echo QT_VERSION=5.15.2 >> $env:GITHUB_ENV

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: C:\Qt
          key: ${{ runner.os }}-Qt-${{ env.QT_VERSION }}-Cache
 
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.QT_VERSION }}
          arch: win64_mingw81
          dir: C:\
          tools: tools_ifw,4.1.1,qt.tools.ifw.41 tools_qtcreator,5.0.2-0,qt.tools.qtcreator,qt.tools.

      - name: Add Qt and MinGW to environment variable
        run: |
          $QT_VERSION1=$env:QT_VERSION
          echo QT_PATH="C:\Qt" >> $env:GITHUB_ENV
          echo MINGW64_BINARY_PATH="C:\msys64\mingw64\bin" >> $env:GITHUB_ENV

      - name: Compile
        run: |
          qmake.exe -o Makefile trdrop\trdrop.pro -spec win32-g++ "CONFIG+=qtquickcompiler" "OBJECTS_DIR=C:\build_temp" "MOC_DIR=C:\build_temp"
          mingw32-make -f Makefile

      - name: Prepare trdrop for artifact
        run: |
          cd $env:MINGW64_BINARY_PATH
          copy-item libgcc_s_seh-1.dll, libstdc++-6.dll, libwinpthread-1.dll, libgomp-1.dll ${env:GITHUB_WORKSPACE}\trdrop-ui\release
          cd ${env:GITHUB_WORKSPACE}
          windeployqt --qmldir trdrop ${env:GITHUB_WORKSPACE}\trdrop-lib\release
          windeployqt --qmldir trdrop ${env:GITHUB_WORKSPACE}\trdrop-tests\release
          windeployqt --qmldir trdrop ${env:GITHUB_WORKSPACE}\trdrop-ui\release

      - name: Run tests
        run: trdrop-tests\release\trdrop-tests.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2 # Todo cleanup release builds. It is very bloated rn.
        if: startsWith(github.event.head_commit.message, 'Release')
        with:
          name: trdrop-v2-dev-${{ env.SHORT_SHA }}
          path: |
            trdrop-lib\release\
            trdrop-tests\release\
            trdrop-ui\release\
          if-no-files-found: error

